### ISSUE TITLE
html embed icons show up vertically

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#352] opened 2019-04-29 17:59 UTC
see https://creativecommons.org/?p=55881&preview=true

cc staff has to be logged into WP to see.

**Comment by janeatcc** [comment] 2019-04-29 19:06
![image](https://user-images.githubusercontent.com/6394777/56920115-3edf8800-6a77-11e9-8070-2a7999f9884c.png)

**Comment by janeatcc** [comment] 2019-04-29 19:15
@kgodey can you tag Hugo in this issue? I can't find him in my list. @brenoferreira thinks it has to do with cc wp styles, so we're going to diagnose this post-flip

**Comment by kgodey** [comment] 2019-04-29 19:18
Added, @hugosolar did not have write permissions to this repository but that's fixed now.

**Comment by hugosolar** [comment] 2019-04-30 03:22
Sorry but I don't have context about this, but this code is generated by cc-search?
I think the problem isn't cc.org's styles because all img elements are displayed as a block and that's fine for most of the content unless you specify right or left alignment.
If each icon element could have a `display: inline-block;` property it will fix the alignment issue

<img width="550" alt="Screen Shot 2019-04-29 at 11 16 06 PM" src="https://user-images.githubusercontent.com/894708/56939310-a1677100-6ad5-11e9-80d5-12052d729126.png">

**Comment by janeatcc** [comment] 2019-04-30 03:56
interesting! @brenoferreira what do you think?

**Comment by janeatcc** [comment] 2019-04-30 03:57
@hugosolar yes, if you try the dev site and try copying html and pasting it into WP that's what you get on cc. see https://ccsearch-dev.creativecommons.org/photos/d383a95c-7bd8-4e3c-a648-b809539ca7f6

**Comment by hugosolar** [comment] 2019-04-30 11:50
Ok, I see it.
I think we have two options here:
- add `display: inline-block;` property to each attribution images
- adding a class to the wrap element and create a custom style on cc.org, but it'll be less generic

**Comment by janeatcc** [comment] 2019-04-30 14:17
Ok -- so this is both an issue with the icons in the html on CC Search and the styling on cc.org? 

@brenoferreira what do you think?

**Comment by brenoferreira** [comment] 2019-04-30 15:28
I agree with @hugosolar to add the `display: inline-block;` to the generated HTML, so it does't require changes on websites that use it

**Comment by janeatcc** [comment] 2019-04-30 15:29
ok, let's try it!

**Closed** 2019-05-01 17:17 UTC
Labels: bug, help wanted
