### ISSUE TITLE
Filters Search Grid Should be closed as soon as filters gets applied on Smartphones.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#680] opened 2020-02-28 20:23 UTC
## Describe the bug
After Applying Filters in the CC Search, it's loading as usual along with the filters grid.

## To Reproduce
1. Go to https://search.creativecommons.org/search?q=apple&license=&license_type=&categories=&extension=&aspect_ratio=wide&size=small&source=&searchBy=
2. Select any filter
3. See error

## Expected behavior
The filters grid should get closed automatically after applying the filters, in order to get better user experience

## Screenshots

![Screenshot_20200229-014137](https://user-images.githubusercontent.com/55599878/75584413-b3b79000-5a95-11ea-8738-9c28502af426.jpg)

## Desktop (please complete the following information)
 - OS: Oxygen OS
 - Browser : Chrome
 - Smartphone : OnePlus 6

## Smartphone 
 - Device: OnePlus 6
 - OS: Oxygen OS
 - Browser: Chrome
 
## Additional context

If it's a legit bug, then would love to work on it! :)

**Comment by annatuma** [comment] 2020-02-28 20:54
@abhisheknaiidu if I'm understanding your description correctly, then this is not a bug. We deliberately leave the left hand filter side bar expanded after a selection has made, unless a user chooses to collapse it. That is, we do not automatically collapse the side bar or any section within it.

FYI @panchovm @brenoferreira so you're aware of this discussion. I'm closing the ticket.

**Closed by annatuma** 2020-02-28 20:54 UTC
