### ISSUE TITLE
search route without any query params is showing a blank search result page

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#853] opened 2020-04-04 14:33 UTC
## Describe the bug
If we don't pass any query params to the `/search` route it displays a black page

## To Reproduce
1. Go to 'https://ccsearch.creativecommons.org/search or got to just `search` route locally'

## Expected behavior
Should fall back to the `page not found` page

## Screenshots
![search_blank](https://user-images.githubusercontent.com/43946715/78453263-25df4e00-76ae-11ea-9f96-b826a0bb9c07.png)

## Desktop
 - OS: Ubuntu 19.10
 - Browser Chrome
 - Version 80.0.3987.162

## Additional context
I want to work on this issue :)

**Comment by abhisheknaiidu** [comment] 2020-04-04 15:24
@hemanth-hk I think It's not an issue actually, because if someone wants to search anything, then he should definately provide some query like :
https://ccsearch.creativecommons.org/search?q=hat

Also taking worst case, if someone intentionally suppose does that, then I think we are providing a search bar for them to search anything, 
Google also does the same way when we **search** route
@akmadian @brenoferreira what are your views in it ?

**Comment by hemanth-hk** [comment] 2020-04-04 15:35
I see that we are passing the `q` as a prop so if someone goes to just `/search` we would be passing undefined and that may create errors in the future cause we are not using `typescript`. So adding a route guard will be helpful in that case

Ya, I can redirect the user to the HomePage

**Comment by abhisheknaiidu** [comment] 2020-04-04 17:17
@hemanth-hk In general, you should not start work on an issue until a mentor or admin has confirmed that it should be move forward with a fix. The issue itself does need to be approved for work first from either any of the CC Staff!

**Comment by hemanth-hk** [comment] 2020-04-04 17:27
Ya, I know that a member has to approve it but, both of us know that this clearly is an issue and surely needs to be fixed. So I just went ahead and fixed it, if there are changes then they can be appended to the `PR` if not we are good to go :)

**Comment by brenoferreira** [comment] 2020-04-06 12:38
I don't see that as a bug. It can even be useful as users can set their filters before searching

**Comment by annatuma** [comment] 2020-04-23 18:32
We discussed this again internally.

In the rare case that a user lands on https://ccsearch.creativecommons.org/search they should be redirected to the CC Search homepage (https://ccsearch.creativecommons.org/) instead of seeing a blank search results page.

Marking this as "help wanted".

**Comment by abhisheknaiidu** [comment] 2020-04-23 18:38
@annatuma Already a PR #855 created for this! It's better if we can open that only! 
If that doesn't satisfies, I am willing to work on it :)

**Comment by abhisheknaiidu** [comment] 2020-04-27 06:26
@annatuma I fixed this in #897

**Closed** 2020-05-12 14:04 UTC
Labels: help wanted
