### ISSUE TITLE
Sharing on Facebook is broken

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#607] opened 2020-02-21 11:11 UTC
## Describe the bug
"Parameter 'href' should represent a valid URL" is the message shown when trying to share an image on Facebook from CC Search.

## To Reproduce
1. Go to https://search.creativecommons.org/photos/7e5b0a9e-47c9-4a0e-829e-915542010c19
2. Under the share tab, click on the Facebook icon.
3. See error

## Screenshots

![cc1](https://user-images.githubusercontent.com/55599878/75029815-ce539d00-54c8-11ea-9be4-e7b70c48064e.png)

## Desktop (please complete the following information)

    OS: Ubuntu 19.10
    Browser: Firefox

**Comment by hemanth-hk** [comment] 2020-02-21 11:27
Please check again cause the same link is working fine for me in  both my browsers
### OS : Ubuntu 19.10

### Browser : Firefox (Version 73.0)
![share-on-fb-firefox](https://user-images.githubusercontent.com/43946715/75030449-2a6af100-54ca-11ea-9c2b-54b5bb09d6e6.png)
### Browser : Chrome (Version 80.0.3987.116)
![share-on-fb-google](https://user-images.githubusercontent.com/43946715/75030451-2dfe7800-54ca-11ea-986d-c3a05a4e37cb.png)

**Comment by hedonhermdev** [comment] 2020-02-21 21:14
Yep, can confirm. Is working in Safari, Chrome and Firefox on my machine.

**Comment by madewithkode** [comment] 2020-02-22 20:32
If this issue has been confirmed to be working fine now, it'd be nice to close it.

**Comment by Aybee5** [comment] 2020-02-23 07:18
Links works perfectly for me.
**OS: UBUNTU 18.04**
**1. Browser: Chrome(Version 79.0.3945.130)**
![Screenshot from 2020-02-23 08-08-48](https://user-images.githubusercontent.com/42099896/75105528-b1c47b80-5614-11ea-88cb-ad871ef34b85.png)
**2. Browser: Firefox(Version 61.0.1)**
![Screenshot from 2020-02-23 08-12-30](https://user-images.githubusercontent.com/42099896/75105553-09fb7d80-5615-11ea-931a-313eddd51e77.png)

**Comment by DantrazTrev** [comment] 2020-02-24 08:47
@abhisheknaiidu The problem is that your redirect to sharer.php has your localhost as its href param . It is not such a case in the live version. I think it's an issue with url redirection on your local build.

**Closed** 2020-02-24 11:05 UTC
Labels: good first issue

**Comment by coderbabu10** [comment] 2020-02-28 18:05
can i take this issue?

**Comment by Aybee5** [comment] 2020-02-28 18:55
> can i take this issue?

The issue is closed
