### ISSUE TITLE
AutoFocus search input field on page load

### ISSUE THREAD

**Issue by akandeBolaji** [creativecommons/cccatalog-frontend#650] opened 2020-02-26 09:53 UTC
## Problem Description

I like it when i visit sites like google.com and i'm able to start typing into the search input immediately without having to tab my keyboard or move my cursor to the input field.

## Solution Description

I would like the  search field to be auto focused on page load to allow faster interactivity

## Additional context

I would like to work on this issue

**Comment by abhisheknaiidu** [comment] 2020-02-27 07:25
@akandeBolaji  I guess It's already exists on CC Search. Do check it once!

**Comment by akandeBolaji** [comment] 2020-02-27 08:50
No, It doesnt exist.
It has autofocus before the page loads completely but all search input value would be cleared and autofocus disabled once page loads completely.
I think i should file this seperately as a bug

**Comment by akmadian** [comment] 2020-02-28 16:43
Closing because I believe that this is a duplicate of #659

**Closed by akmadian** 2020-02-28 16:43 UTC
