### ISSUE TITLE
Make Museum Collections card more Responsive and Interactive.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#688] opened 2020-02-29 20:17 UTC
## Problem Description
The Museum Collection Cards are not so interactive, because we have to click the middle image everytime to make a view request.

## Solution Description 
Rather, we can make the whole card as responsive and interactive, then it provides better User Experience.

![Screenshot_20200301-013505](https://user-images.githubusercontent.com/55599878/75614399-563b4600-5b5e-11ea-96ab-52d1fbed9a1e.jpg)

## Additional context
Would love to Solve :)

**Comment by hemanth-hk** [comment] 2020-03-01 06:50
The CSS is coming from the [vue-vocabulary](https://github.com/creativecommons/vue-vocabulary) project which is under active development so you can change the card styling there which will affect this directly

Do wait for the mentor's response

**Comment by akmadian** [comment] 2020-03-02 23:57
Thanks for your suggestion! I agree with hemanth, although this most likely belongs in [vocabulary](https://github.com/creativecommons/vocabulary)(the source of the CSS used in vue-vocabulary) instead of vue-vocabulary itself. This issue may also be kind of a duplicate of #630 depending on the exact nature of the changes proposed in this issue and 630.

I'm going to close this issue, but in case you get redirected back here, we can always re-open it :)

**Closed by akmadian** 2020-03-02 23:57 UTC
