### ISSUE TITLE
Search result page goes blank after refreshing any random photo details page.   

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#725] opened 2020-03-08 11:21 UTC
## Describe the bug
Search result page goes blank after refresehing any random photo details page.   

## To Reproduce
1. Go to https://ccsearch.creativecommons.org/
2. Search for any image and then click any random image.
3. Refresh the photo detail page and Go Back

## Expected behavior

Results should appear after that also

## Screenshots

![ccw](https://user-images.githubusercontent.com/55599878/76161808-d49a7800-615c-11ea-819a-0063fb1f9104.png)

## Desktop (please complete the following information)
 - OS : Ubuntu
 - Browser Chrome

## Additional context
Want to work on it :)

**Comment by akmadian** [comment] 2020-03-08 19:25
Thanks for reporting this :) I'm gonna close it since it's essentially a duplicate of #673. It's not an exact duplicate, but I think the issue that's causing this will be fixed by work on #673.

**Closed by akmadian** 2020-03-08 19:25 UTC
Labels: bug, not ready for work
