### ISSUE TITLE
Replace google forms for feedback to an on-site form

### ISSUE THREAD

**Issue by AyanChoudhary** [creativecommons/cccatalog-frontend#764] opened 2020-03-15 09:13 UTC
## Problem Description

The google form on the feedback page feels weird because:
a. It does not match the theme of the website and stands out like a sore thumb
b. It has 2 scrollbars, which looks like it is because of the google form itself

![CC Search - Google Chrome 15-03-2020 14_37_42](https://user-images.githubusercontent.com/45792768/76698626-534a6480-66cb-11ea-89b1-a90c523890d5.png)

## Solution Description

Instead of having a google form, we can make a customized form that is better for user experience and also will make the site more consistent as a whole.

## Additional context

I would like to work on this.

**Comment by akmadian** [comment] 2020-03-15 20:32
We want to stick with google forms since it's far easier to set up and use it as opposed to building a custom form page and setting up a db to store responses, and an API to facilitate the addition of responses. The styling doesn't fit perfectly, but the convenience is just too great, and it fits better with CC's larger workflow: we don't use google forms for just bug report and feedback forms.

Part b of the issue is being addressed by #709

**Closed by akmadian** 2020-03-15 20:32 UTC
Labels: enhancement, not ready for work
