### ISSUE TITLE
Alignment of footer in mobile version.

### ISSUE THREAD

**Issue by Dhruvi16** [creativecommons/cccatalog-frontend#623] opened 2020-02-24 08:34 UTC
## Describe the bug
When browsing the mobile version of the website. Footer elements seem to have an uneven margin. 

## To Reproduce
1. Go to 'https://search.creativecommons.org/' on your mobile phone or switch to responsive mode in the browser itself
2. Scroll down to 'footer'

## Expected behavior
```
Icons by The Noun Project.
Website by CC.
Contribute on GitHub.
```
should have same margin as above elements.

## Screenshots
https://search.creativecommons.org/
![image](https://user-images.githubusercontent.com/34674462/75137688-4068f380-570e-11ea-8d0c-e903f5cfd28a.png)

## Desktop (please complete the following information)
 - OS: (Ubuntu 16.04)
 - Browser (Firefox)
 - Version (72.0.2)

**Comment by Dhruvi16** [comment] 2020-02-24 08:34
I am willing to take this up!
Thank you.

**Comment by akmadian** [comment] 2020-02-24 19:33
This may not be relevant because the footer component with the issue is custom, and search is transitioning over to vocabulary, which will standardize the footer component. I'm not sure what the time frame on this is though, so pending approval from @brenoferreira, you may go ahead :)

**Comment by kgodey** [comment] 2020-02-24 20:29
Thanks for finding this bug @Dhruvi16, but I don't think it's worth fixing at the moment. @brenoferreira is working on the new footer this sprint, I think this would be quickly overwritten if implemented.

**Comment by Dhruvi16** [comment] 2020-02-25 03:40
Oh! If that is the case, working on this will be irrelevant for the moment. Thanks for the response @akmadian @kgodey.

**Comment by akmadian** [comment] 2020-02-25 05:39
I'm closing this issue because it doesn't affect functionality, and a fix would be quickly overwritten.

**Closed by akmadian** 2020-02-25 05:39 UTC
