### ISSUE TITLE
Responsive styling issues. 

### ISSUE THREAD

**Issue by ankurshr01** [creativecommons/cccatalog-frontend#674] opened 2020-02-28 13:58 UTC
When we search an image,
INITIAL:- 

![Screenshot (177)](https://user-images.githubusercontent.com/43695296/75554314-1857f800-5a60-11ea-925d-5559cf0bf28f.png)

![Screenshot (176)](https://user-images.githubusercontent.com/43695296/75554338-2443ba00-5a60-11ea-8352-b7ace094a473.png)

FINAL:-  

![Screenshot (174)](https://user-images.githubusercontent.com/43695296/75554462-5f45ed80-5a60-11ea-8608-bad959c68a5d.png)

![Screenshot (175)](https://user-images.githubusercontent.com/43695296/75554472-6240de00-5a60-11ea-808b-428813e1300a.png)

Working!

**Comment by annatuma** [comment] 2020-02-28 15:16
@ankurshr01 please add a written description of the issue, and include what screen size/browser you're seeing the styling issues on. Judging by your screenshots you've fixed this, perhaps locally. Once the description is up to date, we can approve this for work, and you can make a pull request.

**Comment by akmadian** [comment] 2020-02-28 17:17
This may be a duplicate of #625 and #632, for which there is already a PR (see #628).

**Closed** 2020-02-28 17:17 UTC
Labels: duplicate, ticket work required
