### ISSUE TITLE
Add the evaluation of search in the search result page

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#811] opened 2020-03-24 22:04 UTC
We need to add functionality to evaluate the results in the search result page. This function should be placed above top-right in the gallery as the mockup indicates.

### Default state
The `yes` and `no` actions are in the default state.

<img width="349" alt="Screen Shot 2020-03-24 at 19 01 54" src="https://user-images.githubusercontent.com/895819/77481221-f4d76180-6e01-11ea-987b-059e84b861a7.png">

### Option selected
The `yes` option was selected

<img width="332" alt="Screen Shot 2020-03-24 at 19 03 36" src="https://user-images.githubusercontent.com/895819/77481348-39fb9380-6e02-11ea-9a75-434192a4b8d4.png">

**Comment by kgodey** [comment] 2020-03-24 22:07
This is a duplicate of https://github.com/creativecommons/cccatalog-frontend/issues/518.

**Closed** 2020-03-26 12:58 UTC
Labels: Release blocker, urgent
