### ISSUE TITLE
Search results not showing when page load is by history

### ISSUE THREAD

**Issue by akandeBolaji** [creativecommons/cccatalog-frontend#673] opened 2020-02-28 10:03 UTC
## Describe the bug
The search query results do not show when a search query page is visited via the browser history 

## To Reproduce
1. Go to https://ccsearch.creativecommons.org/
2. Type into the search box
3. Click the search button
4. Go back to the home page via the browser history button
5. Go back to the search query page via the browser history button
6. You would notice that no search results display on the page

## Expected behavior
On going back to the search query page via the browser history button, you should be able to view previous results and not an empty page.

## Screenshots
![bandicam 2020-02-28 11-02-23-750](https://user-images.githubusercontent.com/35887799/75539015-de640300-5a19-11ea-80f3-f5161a1e6d42.jpg)
![bandicam 2020-02-28 11-02-14-383](https://user-images.githubusercontent.com/35887799/75539027-e1f78a00-5a19-11ea-8f4a-69b2d80bdbf8.jpg)

## Desktop (please complete the following information)
 - OS: Windows 8.1
 - Browser Chrome
 - Version 80

## Additional context
I would like to work on this issue

**Comment by akmadian** [comment] 2020-02-28 16:57
This is a bug AFAIK, go ahead and investigate this! Please post any findings about what's causing it in this thread before getting started on a fix :)

**Comment by akmadian** [comment] 2020-02-28 17:00
I am not able to replicate this:
OS: Win 10 Pro 1809
Browser: Firefox Dev Ed. 74.0

**Comment by kss682** [comment] 2020-02-28 17:48
I tried the steps to replicate the issue, the search result was showing .
OS : Debian 10
Browser : Chrome
Version : 79

**Comment by DantrazTrev** [comment] 2020-02-28 17:50
I am able to replicate this :
OS: Kali Linux 2020
Browser: Firefox v68.5.0

Here's the issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43457420/75572383-c4a9d680-5a80-11ea-8a1d-b98e8eb8f662.gif)

And here could be one of the solution @akandeBolaji 
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/43457420/75572464-d4c1b600-5a80-11ea-912b-c9313d44f7ba.gif)

Can you confirm?

**Comment by akmadian** [comment] 2020-02-28 17:57
@akandeBolaji do you mean that this occurs when navigating back to it through the browser’s history menu, or when using the forward and back buttons in the upper left?

**Comment by akandeBolaji** [comment] 2020-02-28 17:58
Sorry i wasnt clear in the details, I mean when using the forward and back button

**Comment by akandeBolaji** [comment] 2020-02-28 17:59
@akmadian

**Comment by kss682** [comment] 2020-02-28 18:01
@akandeBolaji then I was able to replicate the issue , I thought it was from history pages.

**Comment by DantrazTrev** [comment] 2020-02-28 18:39
Can I work on this ?

**Comment by akmadian** [comment] 2020-02-28 18:48
This may be (sort of) a duplicate of #662. I'll investigate further and let you know whether or not we want to move forward with getting a fix going.

@DantrazTrev Assuming we want to get a fix going, I'll assign this to @akandeBolaji because they reported this issue and indicated their interest.

**Comment by annatuma** [comment] 2020-02-28 21:38
We've discussed this, and it makes sense to fix this behavior. We should be able to "remember" (i.e. discern) the search query based on the URL on the search results page, so the search box on the homepage should not be empty when you go back to it.

@akmadian I'm making the assignment that you indicated, while I'm in here.

**Closed** 2020-07-16 22:52 UTC
Labels: bug, in progress
