### ISSUE TITLE
Provide multiple search grid options

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#103] opened 2018-10-05 19:05 UTC
Currently, the images in the search grid are displayed at a maximum height of 200px. The images are then centered and cropped horizontally / vertically. This causes certain images, particularly those with images of faces, to be cropped in an undesired fashion. We will offer three options:

- Landscape (currently offered): will add option to display full image.
- Detail view: displays all of image and image details( full attribution, source, license type, etc) without need to rollover.
- Portrait: displays image with higher height to width ratio.  Option to display full image.

**Comment by dhruvkb** [comment] 2019-03-11 23:14
I think the image grid would look particularly great in a [masonry layout](https://masonry.desandro.com/) like that of Pinterest. Are you working on this @sebworks?

**Comment by kgodey** [comment] 2019-03-12 03:06
No one is currently working on this but tagging @janeatcc and @brenoferreira so that they can confirm that it should be worked on since the issue isn't marked "help wanted" or "good first issue".

**Comment by janeatcc** [comment] 2019-03-14 00:48
Yes.. this is in reference to results page right? https://ccsearch.creativecommons.org/search?q=cat&provider&li&lt&searchBy 

Right now we have a checkbox that doesn't make sense to most people "contain image" so this would be a good issue to work on.

**Comment by dhruvkb** [comment] 2019-03-14 04:17
Can I take it up and start working on it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janeatcc** [comment] 2019-03-14 05:53
I am good with it as long as @brenoferreira is!

**Comment by dhruvkb** [comment] 2019-03-22 21:55
@janeatcc @kgodey I raised a PR for this issue a week ago. Looking for reviews and, if all goes well, a merge.

**Comment by chihongya** [comment] 2019-03-24 12:57
。

**Comment by janeatcc** [comment] 2019-04-01 22:57
<img width="1385" alt="Screen Shot 2019-04-01 at 3 55 47 PM" src="https://user-images.githubusercontent.com/6394777/55364744-b7622180-5496-11e9-9171-75b9aac5fc30.png">

When you click "prevent overscaling" and then unclick it, it results in the above, images together with no white spacing

**Comment by kgodey** [comment] 2019-04-01 23:30
@janeatcc can you create a new issue for that?

**Comment by kgodey** [comment] 2019-04-01 23:34
I'm going to close this issue since the work is done (other than addressing the bug above).

**Closed by kgodey** 2019-04-01 23:34 UTC
Labels: enhancement, in progress

**Comment by chihongya** [comment] 2019-04-03 05:35
。
