### ISSUE TITLE
same related images for all search

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#644] opened 2020-02-25 17:17 UTC
## Screenshots
![Screenshot from 2020-02-25 22-47-01](https://user-images.githubusercontent.com/54955755/75270573-c9704f80-5820-11ea-89ff-9aa6504efcec.png)

## Additional context
i would like to take this issue.

**Comment by akmadian** [comment] 2020-02-26 02:59
Maybe I am misunderstanding exactly what you mean, this issue could definitely use some more detail. What are you searching for? Are the related images all the same for a given search term, or for all images, regardless of search term? 

Either way, I cannot reproduce this. Images in the related images section for me are always related to the image I'm viewing, and I've verified this for multiple search terms. I'm going to mark this issue as `ticket work needed` to give you an opportunity to add more detail and clarify what's going on for this issue. If you have not added more detail, or this issue is un-reproducable, I'll close it.

OS: Win 10 Pro 1809
Browser: Firefox Dev Edition 74.0
npm: v6.13.6
node: v12.14.1

**Comment by coderbabu10** [comment] 2020-02-26 04:38
whenever we search for any of the images it shows the same related images everytime no change can be seen in the related image it is not showing the expected behavior.
all the time it shows the same related images,regardless of search terms
OS: Ubuntu 18.04
Browser: Firefox 61.0.1
node: 8.10.0

**Comment by akmadian** [comment] 2020-02-26 06:24
Yeah, that's along the lines of what I thought. I can't reproduce this behavior in dev or production environment so I'm gonna close this issue. If it happens to crop back up, or if someone can reproduce the behavior, I'll let you take point on the fix :)

**Closed by akmadian** 2020-02-26 06:24 UTC
Labels: ticket work required
