### ISSUE TITLE
Image height of over 80,000 px on search results of "search"

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-frontend#423] opened 2019-07-02 17:10 UTC
**Describe the bug**
After a couple of scrolls, the search result of query `search` gives an image which is over 80,000px in height. See the video link below

**To Reproduce**
1. Go to https://search.creativecommons.org/search?q=search&provider&li&lt&searchBy
3. Scroll down a bit.

**Screenshots**
![Screenshot from 2019-07-02 22-36-23](https://user-images.githubusercontent.com/34679965/60532140-3d059f80-9d1a-11e9-9dc0-e5ff720ebc8a.png)
![Screenshot from 2019-07-02 22-37-50](https://user-images.githubusercontent.com/34679965/60532132-38d98200-9d1a-11e9-87df-8560f427214c.png)

**Desktop (please complete the following information):**
 - OS: Linux mint
 - Browser: chrome

**Comment by Atanda1** [comment] 2020-02-21 14:00
Hi guys, I'll like to work on this issue.

**Comment by kgodey** [comment] 2020-02-21 20:30
@Atanda1 I'm not sure if this issue is still relevant given that the design has changed, but if you can reproduce it, feel free to work on it.

**Comment by kgodey** [comment] 2020-02-21 20:30
Please post here if you are working on it.

**Comment by Atanda1** [comment] 2020-02-21 20:38
Okay, but would it be merged officially, because it'll help with my GSoC
application.

**Comment by kgodey** [comment] 2020-02-21 20:40
@Atanda1 we'll evaluate any code you work on, whether it's merged or not. I recommend first checking if you can reproduce this issue and posting here if you're able to reproduce it.

**Comment by Atanda1** [comment] 2020-02-22 10:03
Okay, I'll start working on it.

**Comment by Atanda1** [comment] 2020-02-24 11:43
On my windows machine, there's a ton of eslint errors when I run "npm run dev" about expecting line breaks LF instead of CRLF. I've added *.js text eol=lf to my gitattributes file, according to eslint but its not still going through

**Comment by Atanda1** [comment] 2020-02-24 11:44
http://eslint.org/docs/rules/linebreak-style

Actually linebreak errors

**Comment by kgodey** [comment] 2020-02-24 19:01
@akmadian @brenoferreira

**Comment by Atanda1** [comment] 2020-02-25 10:51
I'm yet to get a response

**Comment by akmadian** [comment] 2020-02-26 02:24
Maybe we could just explicitly disable the rule in eslintrc?

**Comment by Atanda1** [comment] 2020-02-26 02:42
Please do.  I'll really appreciate.

**Comment by akmadian** [comment] 2020-02-26 03:07
@Atanda1 If you would like to create an issue and PR for this, I would be happy to assign you and approve the PR.

**Comment by Atanda1** [comment] 2020-02-26 04:39
So I should create a PR and issue for removing eslint from the project now.

**Comment by Atanda1** [comment] 2020-02-26 04:41
I'll be happy to do that.

**Comment by akmadian** [comment] 2020-02-26 04:47
@Atanda1 No, we are definitely not removing eslint from the project entirely. I just meant adding a line to disable the `linebreak-style` rule in .eslintrc.js

**Comment by Atanda1** [comment] 2020-02-26 04:49
Okay, I get you now. I'll do that.

**Comment by Atanda1** [comment] 2020-02-26 08:47
@akmadian so I should put this "image height" issue on hold for now.

**Comment by Atanda1** [comment] 2020-02-26 11:32
@akmadian here is the issue https://github.com/creativecommons/cccatalog-frontend/issues/649


I've  requested a pull request already.

**Comment by Atanda1** [comment] 2020-02-26 11:43
But on running `npm run dev` it compiles
![Screenshot (92)](https://user-images.githubusercontent.com/45256233/75341756-68cf2a00-5895-11ea-9036-17f69d8ea7f4.png)

And on the browser I get this
![Screenshot (93)](https://user-images.githubusercontent.com/45256233/75341878-9ddb7c80-5895-11ea-91b9-a6947be61646.png)

**Comment by hemanth-hk** [comment] 2020-02-26 12:09
Go to http://localhost:8443/

**Comment by Atanda1** [comment] 2020-02-26 12:48
Thanks. It worked!!

**Comment by Atanda1** [comment] 2020-02-26 17:27
@akmadian heres the pull request https://github.com/creativecommons/cccatalog-frontend/pull/654

**Comment by Atanda1** [comment] 2020-02-28 21:00
My first pull request just got merged,  would be done with the image height
in a bit.

**Comment by abhisheknaiidu** [comment] 2020-04-07 11:32
@kgodey @akmadian After the new Design got merged, I don't think its an issue now, So this can be closed now!

**Closed** 2020-04-07 12:52 UTC
Labels: bug, in progress

**Comment by Atanda1** [comment] 2020-04-07 12:58
Yes, it should.
