### ISSUE TITLE
Better browse capabilities

### ISSUE THREAD

**Issue by little-wow** [creativecommons/cccatalog-frontend#167] opened 2019-01-22 18:28 UTC
I often want to popular browse images from providers, but can't. 

It would be great to be able to browse (and analytics back me up on this – on the old interface, many users submitted empty strings to be able to browse).

This is particularly helpful for huge art collections, like the Met.

**Comment by kgodey** [comment] 2019-04-05 16:45
Duplicate of #168, closing.

**Closed by kgodey** 2019-04-05 16:45 UTC
