### ISSUE TITLE
Clicking Enter while typing in the search-bar hides the filter section

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#852] opened 2020-04-04 11:43 UTC
## Describe the bug
On the search results page when we type something in the search box and hit "Enter" without clicking the search button then it hides the filter section which should not be the case

## To Reproduce

1. Go to 'https://ccsearch.creativecommons.org/search?license=&license_type=&categories=&extension=&aspect_ratio=&size=&source=&q=cats&searchBy= or run locally'
2. Click on 'search bar and hit enter without clicking the search button'
3. See error

## Expected behavior
It should trigger a submit event only

## Screenshots
Something like this will happen
![search_enter](https://user-images.githubusercontent.com/43946715/78445846-f709ad80-7696-11ea-8427-c9ff36f96e0f.png)

## Desktop (please complete the following information)
 - OS: Ubuntu 19.10
 - Browser Chrome
 - Version 80.0.3987.162

## Additional context
Please let me know if anyone else is also able to see this error

I want to work on this :)

**Comment by devRD** [comment] 2020-04-04 12:44
@hemanth-hk I tried reproducing the error, and yes, it seems like the filter section gets hidden for every alternative search.

**Comment by abhisheknaiidu** [comment] 2020-04-04 13:55
@hemanth-hk Yess, its because we actually need to hide the filters in the mobile version after any search is done. Now we actually have same code snippet for filters functionality for both desktop and mobile version. And yea it will get fixed after CC merges #784 and solves #845 
@akmadian @brenoferreira What are your views ?

**Comment by hemanth-hk** [comment] 2020-04-04 13:58
Then I guess we'll have to wait till #784 and see if this error persists or not
Cool, thanks for informing @abhisheknaiidu

**Comment by brenoferreira** [comment] 2020-04-07 12:57
This was fixed in #850

**Closed by brenoferreira** 2020-04-07 12:57 UTC
Labels: awaiting triage, bug
