### ISSUE TITLE
in photo-detail view tabs are not horizontally aligned

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-frontend#678] opened 2020-02-28 18:57 UTC
## To Reproduce
1. Go to 'result'
2. Click on 'image'
3. Scroll down to 'tabs'

## Expected behavior
Tabs should be horizontally aligned

## Screenshots
![Screenshot_2020-02-29 CC Search](https://user-images.githubusercontent.com/35156299/75578624-29b5fa00-5a8a-11ea-8604-eea5fdedb8cb.png)

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
If its a legit issue would like to work on it.

**Comment by akmadian** [comment] 2020-02-28 21:14
If you're referring to the tabs wrapping to a new line, I think it would be better to keep this behavior. I'm not sure what you mean by "horizontally aligned", could you please elaborate, maybe provide a basic mockup of what you mean?

For now, I am adding `ticket work required` to this issue so you can elaborate on what you mean by "horizontally aligned". Once you've elaborated, depending on the scope of these changes, we can work on getting approval for a design change. I saw that there was some changes in these tabs in your PR but didn't realize that they were from changes in #628. I'd say that it's ok to keep these changes in for now, but we may ask you to revert them before merge.

**Comment by annatuma** [comment] 2020-02-28 21:17
Confirming that tabs wrapping to a new line is the intended behavior at this time. I'm happy to review a screenshot or more details as @akmadian suggests.

**Comment by Vineet-Sharma29** [comment] 2020-02-28 23:14
@annatuma , @akmadian apologies for including it in #628 beforehand. With horizontal alignment, I meant to not wrap the tabs. Reason is in mobile view it does not look symmetrical.

**Comment by Vineet-Sharma29** [comment] 2020-03-08 10:48
@annatuma , @akmadian I thought following design:-
- in `xs` view
![Screenshot from 2020-03-08 16-13-32](https://user-images.githubusercontent.com/35156299/76161324-5936c780-6158-11ea-8cd8-6cd5128031a6.png)

- in `sm` view
![Screenshot_2020-03-08 CC Search](https://user-images.githubusercontent.com/35156299/76161328-68b61080-6158-11ea-86e7-2311e008b3e6.png)

**Comment by akmadian** [comment] 2020-03-08 19:28
Thanks for updating this :) I don't think the current design still looks and works better. I'd like to get @annatuma's thoughts, but I'm in favor of keeping the current design and closing this

**Comment by zackkrida** [comment] 2020-06-30 18:55
Hi @Vineet-Sharma29, the design has changed considerably since you created this issue. It no longer appears to be a problem with our new tab style, so I'm going to close the issue. Thank you for your contribution!

**Closed by zackkrida** 2020-06-30 18:55 UTC
Labels: ticket work required
