### ISSUE TITLE
Reloading error of the search results.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#664] opened 2020-02-27 19:02 UTC
## Describe the bug
After the issue #662 (after refreshing) when you go back then you will see that there is no images , not as you expected to have your previous search and after refreshing then it shows the images again i think it is a big issue and can cause difficulties for the users.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/54955755/75480231-e6df1e00-59c6-11ea-80bc-207c004ff24a.gif)

## Expected behavior
we expect to have the previous search results but it shows nothing.

## Additional context
If it's a issue, i would like to take this up.

**Comment by akmadian** [comment] 2020-02-28 16:48
Please see [Breno's comment on the other time you posted this issue](https://github.com/creativecommons/cccatalog-frontend/issues/662#issuecomment-592137018).

I'm closing this issue because it's a duplicate of #662.

**Closed by akmadian** 2020-02-28 16:48 UTC
